### PR TITLE
T0003 - Converter reading structure

### PR DESCRIPTION
**Pull request by heinezen**
New blogpost about the new openage converter.

### CODE REVIEW

**Review by TheJJ — COMMENTED** [review]
Looking very good :)
The images are still named `C0000*`, should be `T0003*`.

**Comment by heinezen** [comment]
Done and ready to merge :)

**Review by TheJJ — APPROVED** [review]
looking great!

**Comment by TheJJ** [comment]
ah, please merge the commits and update the commit message, it's still C0000

**Pull request merged**
